Pendulum-v1:
  policy: "MlpPolicy"
  n_timesteps: 100000

LunarLanderContinuous-v3:
  policy: "MlpPolicy"
  n_timesteps: 100000

# Tuned
Ant-v5:
  policy: "MlpPolicy"
  n_timesteps: 100000
  n_steps: 1024
  gamma: 0.95
  learning_rate: 0.00016954985849969043
  n_critic_updates: 10
  cg_max_steps: 10
  target_kl: 0.03
  gae_lambda: 0.8
  batch_size: 64
  net_arch: small
  activation_fn: tanh
  ent_coef: 0.0008
  buffer_capacity: 93000
  reward_threshold: 350.0
  replay_strategy_threshold: -3.856011224961875
  epsilon: 0.85

Humanoid-v5:
  policy: "MlpPolicy"
  n_timesteps: 100000

InvertedDoublePendulum-v5:
  policy: "MlpPolicy"
  n_timesteps: 100000

RocketLander-v0:
  policy: "MlpPolicy"
  n_timesteps: 100000