Pendulum-v1:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  n_steps: 1024
  n_critic_updates: 20

# Tuned
LunarLanderContinuous-v3:
  batch_size: 16
  n_steps: 512
  gamma: 0.9
  learning_rate: 1.814676598388671e-05
  n_critic_updates: 20
  cg_max_steps: 25
  target_kl: 0.03
  gae_lambda: 0.98
  net_arch: small
  activation_fn: relu
  ent_coef: 0.0001
  buffer_capacity: 93000
  max_env_reward: 350.0
  reward_threshold: 0.92

Ant-v5:
  policy: 'MlpPolicy'
  batch_size: 256
  n_steps: 512
  gamma: 0.98
  learning_rate: 0.00013884520238121
  n_critic_updates: 30
  cg_max_steps: 30
  target_kl: 0.005
  gae_lambda: 0.98
  net_arch: medium
  activation_fn: tanh
  ent_coef: 0.0007
  buffer_capacity: 94000
  max_env_reward: 600.0
  reward_threshold: 0.99

Humanoid-v3:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  ent_coef: 0.01

InvertedDoublePendulum-v5:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  ent_coef: 0.01

RocketLander-v0:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  ent_coef: 0.01

