
Pendulum-v1:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  learning_rate: !!float 1e-3


LunarLanderContinuous-v3
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 256
  learning_rate: lin_7.3e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000

Ant-v5
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 256
  learning_rate: lin_7.3e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000

Humanoid-v3
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 256
  learning_rate: lin_7.3e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000

InvertedDoublePendulum-v5
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 256
  learning_rate: lin_7.3e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000

RocketLander-v0
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 256
  learning_rate: lin_7.3e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000