
# Tuned
LunarLanderContinuous-v3:
  n_envs: 2
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  batch_size: 32
  n_steps: 512
  gamma: 0.9999
  learning_rate: 0.0009
  n_critic_updates: 20
  cg_max_steps: 25
  target_kl: 0.005
  gae_lambda: 0.99
  n_quantiles: 50
  truncation_threshold: 5
  n_value_networks: 5

Ant-v5:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  ent_coef: 0.01

Humanoid-v3:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  ent_coef: 0.01

InvertedDoublePendulum-v5:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  ent_coef: 0.01

RocketLander-v0:
  normalize: true
  n_envs: 2
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  ent_coef: 0.01

